### ISSUE TITLE
Multi-modal chat with `gemini-pro-vision`

### ISSUE THREAD

**Issue by muddi900** [google-gemini/generative-ai-dart#131]
I am trying to build a multimodal chat component for my app. However, you can't have a text only input in 'gemini-pro-vision' `ChatSession`.

We should be able to have a chat that includes text-only input and multi-modal inputs.

**Comment by natebosch** [comment]
I believe this is a known issue, but I'm not aware of the specific plans for changes here. Questions about the backend and model behavior can be directed to https://discuss.ai.google.dev/

Closing this issue for now since this issue tracker relates to the Dart implementation.
