### ISSUE TITLE
Pub not pulling correct build

### ISSUE THREAD

**Issue by WarrenNkomanga** [google-gemini/generative-ai-dart#161]
### Description of the bug:

running $ flutter pub add google_generative_ai is currently pulling google_generative_ai: ^0.0.1-dev instead of version 0.4.0

**Comment by devoncarew** [comment]
`dart pub add` should get the latest version that resolves into your project. It's possible there are other deps in your project which are constraining the version solve. Can you post which version of the dart sdk you're using?
