### ISSUE TITLE
Error 500 (internal error) while prompting with function call

### ISSUE THREAD

**Issue by hmduc1603** [google-gemini/generative-ai-dart#166]
### Description of the bug:

During prompting with function call, it randomly return 500 error (only about 8/10 requests are successful).

> [log] An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting

Here my model declaration:

<img width="470" alt="Screenshot 2024-05-16 at 15 28 01" src="https://github.com/google-gemini/generative-ai-dart/assets/90256010/1a6a7088-30e0-4d99-96ba-b58f1ce01ccb">

**Comment by singhniraj08** [comment]
@hmduc1603,

Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to Dart SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by hmduc1603** [comment]
Thanks, it's normal now!
