### ISSUE TITLE
Multi content doesn't work with google generative ai flutter package

### ISSUE THREAD

**Issue by ilyesksr** [google-gemini/generative-ai-dart#178]
### Description of the bug:

hello guy pls can some one help me when i use google generative ai package with gemini-1.5-flash model with text only the app work normally but when i try to add an image as an entry i get this error
An internal error has occurred. Please retry or report in [https://developers.generativeai.google/guide/troubleshooting](https://developers.generativeai.google/guide/troubleshooting?fbclid=IwZXh0bgNhZW0CMTAAAR3SB_PcXu7LJ-RFGxJWg5pjf7OP2b4CMRAztrlwPCSTXJuVy9vDzeUTHJI_aem_ATqYftTw5JSivLwmAFlXizeZYVJSgSYNagWhAjDo7tLhq4t_Kx-PZoQAH16FhvRlbsbYLUgb2PQZOKu1dkCbghD9)
error
sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_ packages/google_generative_ai/src/api.dart 583:54                            parseGenerateContentResponse
here is the code :
```
List<Part> parts = [TextPart(message)];
try {
if (image != null) {
parts.add(DataPart(image.extension!, image.bytes!));
}
} catch (e) {
log(e.toString());
}
var content = Content.multi(parts);
var response = myChat.sendMessageStream(content);
```

### Actual vs expected behavior:

it supposed to work on both text only and text with image but currently it work with text only

**Comment by fatiq17irenictech** [comment]
my add image function is working fine:
if (_selectedImage != null) {
            final model = GenerativeModel(
                model: 'gemini-pro-vision', 
                apiKey:"your api key",
            );

            final imageBytes = await _selectedImage!.readAsBytes();
            final content = Content.multi([
                TextPart("your message"),
                DataPart('image/jpeg', imageBytes),
            ]);

            final response = await model.generateContent([content]);

**Comment by natebosch** [comment]
This looks like a backend error unrelated to the SDK. Hopefully this was transient, but if this is still happening the best place to get help is at the https://developers.generativeai.google/guide/troubleshooting link form the error message.
