### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by VivekSorathiyaa** [google-gemini/generative-ai-dart#183]
### Description of the bug:

Target of URI doesn't exist: 'package:google_generative_ai/google_generative_ai.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
library package:google_generative_ai/google_generative_ai.dart
package:google_generative_ai/google_generative_ai.dart

**Comment by natebosch** [comment]
See https://github.com/google-gemini/generative-ai-dart?tab=readme-ov-file#using-the-sdk-in-your-own-app

This package needs to be a dependency listed in `pubspec.yaml` and the packages updated. `dart pub add` or `flutter pub add` should handle this.
