### ISSUE TITLE
Files API

### ISSUE THREAD

**Issue by blambe** [google-gemini/generative-ai-dart#211]
### Description of the feature request:

Perhaps I am missing this, but I haven't found a way to access the Gemini Files API from the Dart SDK. Asking Gemini how to do it produced an answer suggesting using a package named Gemini from pub.dev which has nothing to do with google-gemini.

![image](https://github.com/user-attachments/assets/c344d9ec-9781-447c-ab8e-3f40d1702201)

### What problem are you trying to solve with this feature?

Upload larger files into the Files API for use with generative AI

**Comment by MrCsabaToth** [comment]
Please don't say this is not part of the package. There's no other way to handle audio or video!

**Comment by MrCsabaToth** [comment]
Note this closed ticket: #70

**Comment by natebosch** [comment]
Our current recommendation for use cases that need functionality beyond what is provided in this package is to use vertex AI through https://pub.dev/documentation/firebase_vertexai/latest/

**Comment by natebosch** [comment]
Closing as a duplicate of #70
