### ISSUE TITLE
Facilitate the use of the Gemma LLM

### ISSUE THREAD

**Issue by FMorschel** [google-gemini/generative-ai-dart#87]
Facilitate the use of the Gemma model. Since it has launched, I believe that [Gemma](https://ai.google.dev/gemma) should be integrated with this SDK.

**Comment by natebosch** [comment]
The package which will expose support for on device models is https://pub.dev/packages/mediapipe_genai

I'll close this request in this tracker because this SDK is intended to support the server based models.
